### ISSUE TITLE
Wrong spacing before punctuation characters in Nerd Font version

### ISSUE THREAD

**Issue by IgorKrupenja** [cseelus/monego#3] opened 2019-11-05 15:59 UTC
1. Install Monego Nerd Font on a Mac.
2. Enable the font in an app (reproducible at least in iTerm and VSCode).
3. Try typing something containing some punctuation, e.g. `"This is a test:'`.

![image](https://user-images.githubusercontent.com/26354715/68223724-fb517200-fff5-11e9-8230-5ff49377175c.png)

Notice how `:` and `'` look as if there is a space in front of them even though there isn't.

**Comment by cseelus** [comment] 2019-11-05 18:02
Hey @krupenja. The issue seems to [stem from Ligaturizer](https://github.com/ToxicFrog/Ligaturizer/issues/74). Does [this](https://github.com/cseelus/monego/files/3810551/Monego.Nerd.Font.without.Ligatures.zip) version without ligatures work for you?

**Comment by IgorKrupenja** [comment] 2019-11-08 15:44
No, sorry, the problem persists even with the version without ligatures from your comment.

**Comment by prashaantt** [comment] 2020-03-07 07:57
Reporting in with the same issues.

Liga Monego/Monego Nerd Font:

![image](https://user-images.githubusercontent.com/390540/76139539-e144a080-6076-11ea-8cbf-4eb7f86ecd3c.png)

Monego:

![image](https://user-images.githubusercontent.com/390540/76139555-0b965e00-6077-11ea-92f2-01c90a6e5c14.png)

Notice the different kerning in `erv`, `.` and `;`.

Otherwise I really dig your font. Have you been able to figure a fix for this yet @cseelus?

**Comment by cseelus** [comment] 2020-03-09 17:19
@prashaantt Currently I'm not using Monego, so I can't test, but PRs are welcome.

**Comment by matteematt** [comment] 2021-01-08 19:33
Did anyone ever find a fix for this because I just downloaded them and I am having the same issue

**Comment by matteematt** [comment] 2022-03-03 09:48
Any movement on this?

**Comment by cseelus** [comment] 2022-03-03 16:39
I've just recreated the Nerd Font version with different ligature settings, as the kerning issues are caused by Ligaturizer (see my comment above). Still not ideal, but unless the Ligaturizer kerning issue is resolved, there is not much I can do about it.

**Comment by matteematt** [comment] 2022-03-05 16:23
Hi I am going to try look into this issue myself, but I need to ask a few questions to kind of know where to start. I see in the linked comment [here](https://github.com/ToxicFrog/Ligaturizer/issues/74) that the issue seems to be from using the ligatures. Am I correct in thinking that ligatures are the things where a syntax such as `=>` gets turned into one arrow symbol? If so, why does the nerd font that doesn't have the ligatures have the issue? Or does the nerd font automatically create the ligatures?

**Comment by cseelus** [comment] 2022-03-05 18:00
Hi @matteematt, the Nerd Font version is based on the version with the ligatures and yes, those are special characters that replace `=>` and others.
Did you test the new version?

**Comment by matteematt** [comment] 2022-03-05 20:25
@cseelus yeah unfortunately it still seems like an issue. It seems to affect hardly any of the symbols but unfortunately with it affecting the `.` symbol which is used loads in programming it makes it look very strange
I don't know anything about fonts, ligatures, and kerning. So going to have to learn about it and see if I can come up with anything. Will be unlikely but I really like the font so I think it is worth a go

**Comment by cseelus** [comment] 2022-03-05 21:04
I'm on macOS and the dot seems to be looking good now:
<img width="204" alt="Screen Shot 2022-03-05 at 21 58 08" src="https://user-images.githubusercontent.com/3188392/156899748-0a818f1d-2775-42b1-bd01-5f8bf9baf87f.png">


Here are some other programming fonts, for comparision:

<img width="196" alt="Screen Shot 2022-03-05 at 21 57 12" src="https://user-images.githubusercontent.com/3188392/156899733-0e35ac8f-79c2-4592-8d9f-bfebfedf0dbc.png">  [Menlo](https://en.wikipedia.org/wiki/Menlo_(typeface)) (macOS monospace font that followed after Monaco)  

<img width="194" alt="Screen Shot 2022-03-05 at 21 56 48" src="https://user-images.githubusercontent.com/3188392/156899722-6a022c98-0786-4228-bdb0-d5679d70aa1f.png">  PT Mono

Still, the letter-spacing/kerning isn't optimal, so if you manage to improve upon the current state with [Ligaturizer](https://github.com/ToxicFrog/Ligaturizer) and [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts), I'd be more than happy to merge it.

**Comment by matteematt** [comment] 2022-03-06 19:46
I haven't checked MacOS (can check tomorrow once I use my work laptop). This is the issue I am seeing on my PC though (Arch Linux + Alacritty)
![before_1](https://user-images.githubusercontent.com/43502076/156939449-f552c3a3-5824-4edc-b3b9-d122ade91db4.png)
![before_2](https://user-images.githubusercontent.com/43502076/156939453-7112f2a6-8a21-4694-9886-11007cce24ca.png)
You can really notice the issue with the placeholder symbols I am using to represent spaces in the yaml files, but you can also see in the Haskell file that the dot on line 29 is very obviously mismatched (same with the `#` and some other symbols).

I have made some progress and I have tested it on machine and it looks good to me. Here are the same two examples.
 
![after_1](https://user-images.githubusercontent.com/43502076/156939513-b59c0d6a-533e-479e-b5fc-2cb78a7ec613.png)
![after_2](https://user-images.githubusercontent.com/43502076/156939516-4b484af5-6385-4ef1-bc9e-b4e852095a08.png)

I was going to make a draft PR so you could check them on your machine (or so I could check them on my Mac) but it seems I don't have rights to push to this repo. Is that something you need to allow, or do I need to make a PR another way? Sorry I haven't really contributed to any public repos before

**Comment by matteematt** [comment] 2022-03-06 20:13
Another issue I would like to fix too is the font underlining. Here is a font with underlining that you can see goes underneath the text
![image](https://user-images.githubusercontent.com/43502076/156940422-da01cd3c-bd33-415a-b70b-6d3a68e5c2ed.png)
But the underlining seems to intersect with the text in this font slightly
![image](https://user-images.githubusercontent.com/43502076/156940473-6f2add1b-a2a2-41b0-bf4f-cb0f3426b0dd.png)

**Comment by matteematt** [comment] 2022-03-06 20:21
Fixed that too I think 
![image](https://user-images.githubusercontent.com/43502076/156940712-d4d58b79-401c-42be-8c78-34641878c80a.png)

**Comment by cseelus** [comment] 2022-03-06 21:33
@matteematt, seems you made great progress improving the font. I’ll check it out when I’m back in my computer.

To make a PR in a public Github repo, you have to follow these steps: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by cseelus** [comment] 2022-03-06 23:00
@matteematt I‘ve added you as a collaborator, so you should be able to open a PR here directly.

**Comment by matteematt** [comment] 2022-03-07 08:05
@cseelus I have created a PR with the fixed nerd font. Feel free to test it out and let me know any issues. I have now tested on MacOS too and it seems to work fine. However, I have noticed the ligature symbols themselves are still not fixed - more info on the PR. I personally don't use ligatures though

**Closed as completed** 2022-04-02 13:11 UTC
